new file:   connect.sh 	new file:   transcript/COMP2345-2018.txt 	modified:   transcript/transcript

diff --git a/transcript/transcript b/transcript/transcript
--- a/transcript/transcript
+++ b/transcript/transcript
@@ -1,32 +1,39 @@
 #!/bin/bash
+
+# help message
 usage()
 {
-	echo "Student Transcript Generator 6.7.2"
+	echo "Student Transcript Generator 1.0.0"
 	echo "Copyright © 2021 WANG Meng SID: 19078543d"
 	echo "Visit Github https://github.com/Moenupa for author details"
 	echo
-	echo "Usage: generate student transcript based on 'comp[0-9a-zA-Z]*-[0-9]*.txt' files"
+	echo "Usage: ./transcript [name]"
+	echo "generate student transcript for parameter [name], if none then generate for all possible"
+	echo "data from files REGEX\`$dataRegEx\` in posix-extended"
+	echo
 	echo "Actions:"
 	echo "  -help                get help"
 }
-if [[ $* == "--help" || $* == "-help" ]]; then usage; exit; fi
 
 # global dir for tmp files
-tmpDir=/tmp/transcript
+tmpDir="/tmp/$(echo $UID | md5sum | awk '{print $1}')"
+dataRegEx="./[comp|COMP][0-9a-zA-Z]+-[0-9]{4}.txt"
+
+if [[ $* == "--help" || $* == "-help" ]]; then usage; exit; fi
 
 # generate md5 sum of matched data files
 generateMD5()
 {
-	touch $tmpDir/data.md5sum
-	md5sum $(find . -type f -regex './comp[0-9a-zA-Z]*-[0-9]*.txt' -exec echo {} \;) > $tmpDir/$1.md5sum
+	touch $tmpDir/$1.md5sum
+	md5sum $(find . -type f -regextype posix-extended -regex $dataRegEx -exec echo {} \;) > $tmpDir/$1.md5sum
 }
 
-# change data format to:
-# $ cat name 
+# change data format, output to tmpFile in tmpDir:
+# $ cat $tmpDir/name.dat 
 # year subject credit grade
 preprocessing()
 {
-	for f in `find . -type f -regex './comp[a-zA-Z0-9]*-[0-9]*.txt' | sort`; do 
+	for f in `find . -type f -regextype posix-extended -regex $dataRegEx | sort`; do 
 		sed '1d' $f | while read name grade; do
 			if ! test -f $tmpDir/$name.dat; then touch $tmpDir/$name.dat; fi
 			echo "$(head -n 1 $f | awk '{if ($3!="") {print $2,$1,$3} else {print $2,$1,"3"}}') $grade" >> "$tmpDir/$name.dat"
@@ -34,6 +41,7 @@ preprocessing()
 	done 
 }
 
+# initialize the environment
 init()
 {
 	if ! test -d $tmpDir; then
@@ -104,13 +112,14 @@ genTranscript()
 	awk -f $tmpDir/GP.awk $1
 }
 
+# main body
 init
 if [ $# -gt 0 ]; then 
-	for arg in $@; do
-		if ! test -f $tmpDir/$arg.dat; then
-			echo "Warning: transcript for Student '$arg' is invalid"
+	for stu in $@; do
+		if ! test -f $tmpDir/$stu.dat; then
+			echo "==> warning: transcript for student '$stu' is invalid"
 		else 
-			genTranscript "$tmpDir/$arg.dat"
+			genTranscript "$tmpDir/$stu.dat"
 		fi
 	done
 else
